CREATE USER C##SCHOOL IDENTIFIED BY "LKPW3XVj8crFUB-6CY_f";
GRANT CONNECT, RESOURCE TO C##SCHOOL;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO C##SCHOOL;
ALTER USER C##SCHOOL QUOTA UNLIMITED ON USERS;