CREATE TABLE C##SCHOOL.STUDENTS(
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY
        (START WITH 6 MINVALUE 1 NOMAXVALUE INCREMENT BY 1 NOCYCLE),
	UUID VARCHAR2(36) NOT NULL UNIQUE,
	NAME VARCHAR2(100) NOT NULL,
    AGE NUMBER(3, 0) NOT NULL,
    GRADE NUMBER(2, 0) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    ACTIVE_STUDENT VARCHAR2(1) NOT NULL CHECK (ACTIVE_STUDENT IN ('Y', 'N')),
    FOREIGN_STUDENT VARCHAR2(1) NOT NULL CHECK (FOREIGN_STUDENT IN ('Y', 'N')),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY("ID")
);
/

CREATE TABLE C##SCHOOL.USERS(
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 MINVALUE 1 NOMAXVALUE INCREMENT BY 1 NOCYCLE),
	UUID VARCHAR2(36) NOT NULL UNIQUE,
	NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY("ID")
);
/

INSERT INTO
    C##SCHOOL.USERS (
        ID,
        UUID,
        NAME,
        EMAIL,
        PASSWORD,
        CREATED_AT,
        UPDATED_AT
    )
VALUES (
        1,
        'c7622fd7-b680-4e40-83f4-1161d67c81e3',
        'Antonio Zarate Rosas',
        'azr230502@gmail.com',
        '$2a$10$jvBebL3YAy/BwYVP8HIZBeDbX.BytMflCwte2Js6wUOy1v3ufLjaG', -- 0000
        TIMESTAMP '2025-03-10 14:58:59.984068',
        TIMESTAMP '2025-03-10 14:58:59.984068'
    ), (
        2,
        '7d462d0d-0273-4c77-b74b-eb83d4733855',
        'Fernanda Reyes Salinas',
        'fernanda@gmail.com',
        '$2a$10$K3UglfSUmmZYHofFlHEcE.fZsxc6GoKTUB6KFfOZiY0p5QBfvO4NO', -- 1111
        TIMESTAMP '2025-03-10 15:01:33.695055',
        TIMESTAMP '2025-03-10 15:01:33.695055'
    );
/

INSERT INTO
    C##SCHOOL.STUDENTS (
        ID,
        UUID,
        NAME,
        AGE,
        GRADE,
        ADDRESS,
        ACTIVE_STUDENT,
        FOREIGN_STUDENT,
        CREATED_AT,
        UPDATED_AT
    )
VALUES (
        1,
        '7d462d0d-0273-4c77-b74b-eb83d4733855',
        'Danira Belem Aquino Yepez',
        22,
        5,
        'Korea',
        'Y',
        'Y',
        TIMESTAMP '2025-03-10 15:31:29.634391',
        TIMESTAMP '2025-03-10 15:31:29.634391'
    ), (
        2,
        '7cebc3a9-b41b-4cad-a077-7d3f010cfdc4',
        'Rubén Camacho Álvarez',
        22,
        5,
        'Pachuca',
        'Y',
        'N',
        TIMESTAMP '2025-03-10 15:31:29.886713',
        TIMESTAMP '2025-03-10 15:31:29.886713'
    ), (
        3,
        'a8efc394-0da2-4d7c-817a-442e3f924131',
        'Lorena Itzel Sánchez Pesqueda',
        23,
        6,
        'Nezahualcoyotl',
        'Y',
        'N',
        TIMESTAMP '2025-03-10 15:31:29.997058',
        TIMESTAMP '2025-03-10 15:31:29.997058'
    ), (
        4,
        '6d824ecd-7dd7-41c3-88fd-a2fc683d2c7f',
        'Cesar Mauricio Salcedo Jimenez',
        21,
        7,
        'Zumpango',
        'Y',
        'N',
        TIMESTAMP '2025-03-10 15:31:30.093428',
        TIMESTAMP '2025-03-10 15:31:30.093428'
    ), (
        5,
        'eb6eb290-2b97-4c3b-a49e-eb0c4c2927ff',
        'Atenea Collado Martínez',
        20,
        8,
        'Nueva York',
        'Y',
        'Y',
        TIMESTAMP '2025-03-10 15:31:30.194875',
        TIMESTAMP '2025-03-10 15:31:30.194875'
    );