CREATE OR REPLACE PROCEDURE C##SCHOOL.SP_FILTER_STUDENTS(P_FILTER_TYPE IN VARCHAR2, P_FILTER_VALUE IN VARCHAR2, P_RESULT OUT SYS_REFCURSOR)
AS BEGIN
	CASE P_FILTER_TYPE
		WHEN 'active' THEN
			OPEN P_RESULT FOR
				SELECT * FROM C##SCHOOL.STUDENTS WHERE ACTIVE_STUDENT = UPPER(P_FILTER_VALUE);
		WHEN 'foreign' THEN
			OPEN P_RESULT FOR
				SELECT * FROM C##SCHOOL.STUDENTS WHERE FOREIGN_STUDENT = UPPER(P_FILTER_VALUE);
		WHEN 'name' THEN
			OPEN P_RESULT FOR
				SELECT * FROM C##SCHOOL.STUDENTS WHERE UPPER(NAME) LIKE '%' || UPPER(P_FILTER_VALUE) || '%';
		WHEN 'age' THEN
			OPEN P_RESULT FOR
				SELECT * FROM C##SCHOOL.STUDENTS WHERE AGE = TO_NUMBER(P_FILTER_VALUE);
		WHEN 'grade' THEN
			OPEN P_RESULT FOR
				SELECT * FROM C##SCHOOL.STUDENTS WHERE GRADE = TO_NUMBER(P_FILTER_VALUE);
		ELSE
            OPEN P_RESULT FOR
                SELECT * FROM C##SCHOOL.STUDENTS WHERE 1 = 0;
	END CASE;
END;