CREATE OR REPLACE PROCEDURE C##SCHOOL.SP_UPDATE_STUDENT(
	P_UUID IN VARCHAR2,
	P_NAME IN VARCHAR2,
	P_AGE IN NUMBER,
	P_GRADE IN NUMBER,
	P_ADDRESS IN VARCHAR2,
	P_FOREIGN_STUDENT IN VARCHAR2
) AS BEGIN
	UPDATE
		C##SCHOOL.STUDENTS
	SET
		NAME = P_NAME,
		AGE = P_AGE,
		GRADE = P_GRADE,
		ADDRESS = P_ADDRESS,
		ACTIVE_STUDENT = 'Y',
		FOREIGN_STUDENT = P_FOREIGN_STUDENT,
		UPDATED_AT = CURRENT_TIMESTAMP
	WHERE
		UUID = P_UUID;
END;