CREATE OR REPLACE PROCEDURE C##SCHOOL.SP_INSERT_STUDENT(
	P_UUID IN VARCHAR2,
	P_NAME IN VARCHAR2,
	P_AGE IN NUMBER,
	P_GRADE IN NUMBER,
	P_ADDRESS IN VARCHAR2,
	P_FOREIGN_STUDENT IN VARCHAR2
) AS BEGIN
	INSERT INTO "C##SCHOOL".STUDENTS
		(UUID, NAME, AGE, GRADE, ADDRESS, ACTIVE_STUDENT, FOREIGN_STUDENT)
	VALUES
		(P_UUID, P_NAME, P_AGE, P_GRADE, P_ADDRESS, 'Y', P_FOREIGN_STUDENT);
END;