CREATE OR REPLACE PROCEDURE C##SCHOOL.SP_UNENROLLING_STUDENT(
	P_UUID IN VARCHAR2
) AS BEGIN
	UPDATE
		C##SCHOOL.STUDENTS
	SET
		ACTIVE_STUDENT = 'N',
		UPDATED_AT = CURRENT_TIMESTAMP
	WHERE
		UUID = P_UUID;
END;